/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package selenium.java.task;

// import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.*;

//import selenium.java.task.driver.DriverFactory;

import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.Map;

/**
 *
 */
public class AppTest {

        public WebDriver chromeDriver;

        @BeforeClass
        public void testSetup() {
                // this.chromeDriver = new DriverFactory().createInstance();
                System.setProperty("webdriver.chrome.driver",
                                "/Users/tejaswini/workspace/java-selenium-tutorialspoint/app/src/main/resources/chromedriver");
                this.chromeDriver = new ChromeDriver();
                this.chromeDriver.manage().window().maximize();

        }

        @DataProvider(name = "users")
        public Object[][] getData() {
                return new Object[][] {
                                { "Helena", "Parker", "Male", 1, "05/01/2022", "Manual Tester", "RC", "Europe", 1, 1,
                                                "app/src/test/resources/auto.png" },
                                // { "Helena", "Parker", "Male", 5, "05/01/2022", "Manual Tester", "RC",
                                // "Europe", 2, 2 }
                };
        }

        @BeforeMethod
        public void loadURL() {
                this.chromeDriver.get("https://www.tutorialspoint.com/selenium/selenium_automation_practice.htm");
                WebDriverWait waitToLoad = new WebDriverWait(chromeDriver, Duration.ofSeconds(5));
                waitToLoad.until(ExpectedConditions.elementToBeClickable(By.xpath("//input[@value='RC']")));
        }

        @Test(priority = 1, dataProvider = "users", description = "")
        public void verifyFormWithCorrectValues(String firstName, String lastName, String gender, int yearsOfExperience,
                        String date, String profession, String flavours, String continent, int seleniumCommand,
                        int testCount, String imagePath)
                        throws MalformedURLException, UnsupportedEncodingException {
                App app = new App(this.chromeDriver);
                app.setFirstName(firstName);
                app.setLastName(lastName);
                app.genderSelection(gender);
                app.setYearsOfExperience(yearsOfExperience);
                app.setDate(date);
                app.setProfession(profession);
                // app.uploadImage(imagePath);
                app.setFlavoursOfSelenium(flavours);
                app.setContinents(continent);
                app.setSeleniumCommands(seleniumCommand);
                app.clickButton();
                app.acceptSubmitAlert();
                app.pointToNewTab(testCount);
                URL submittedFormURL = app.getCurrentURL();
                System.out.println(submittedFormURL.toString());
                Map<String, String> queryPairs = app.splitQuery(submittedFormURL);
                Assert.assertEquals(queryPairs.get("firstname"), firstName);
                Assert.assertEquals(queryPairs.get("lastname"), lastName);
                Assert.assertEquals(queryPairs.get("sex"), gender);
                Assert.assertEquals(queryPairs.get("exp"), yearsOfExperience);
                Assert.assertEquals(queryPairs.get("profession"), profession);
                Assert.assertEquals(queryPairs.get("tool"), flavours);
                Assert.assertEquals(queryPairs.get("continents"), continent);
                Assert.assertEquals(queryPairs.get("selenium_commands"), seleniumCommand);

        }

        @AfterClass
        public void closeBrowser() {
                chromeDriver.quit();
        }
}
